---
dependencies:
- name: reporting-operator
  version: 0.1.0
  repository: "file://../reporting-operator"
- name: openshift-reporting
  version: 0.1.0
  repository: "file://../openshift-reporting"
  condition: openshift-reporting.enabled
- name: presto
  version: 0.1.0
  repository: "file://../presto"
- name: hdfs
  version: 0.1.0
  repository: "file://../hdfs"
  condition: hdfs.enabled
- name: superset
  version: 1.0.0
  repository: "file://../superset"
  condition: superset.enabled
