reporting-operator:
  spec:
    config:
      prometheusURL: "https://prometheus-k8s.openshift-monitoring.svc:9091/"
      tls:
        enabled: true
        createSecret: false
        secretName: "reporting-operator-tls-secrets"
    service:
      annotations:
        "service.alpha.openshift.io/serving-cert-secret-name": "reporting-operator-tls-secrets"
    image:
      tag: latest

presto:
  spec:
    presto:
      securityContext:
        fsGroup: null
    hive:
      securityContext:
        fsGroup: null
hdfs:
  spec:
    enabled: true
    config:
      datanodeDataDirPerms: "775"

    securityContext:
      fsGroup: null
