apiVersion: chargeback.coreos.com/prealpha
kind: ReportDataStore
metadata:
  name: "pod-memory-usage"
  labels:
    tectonic-chargeback: "true"
spec:
  storage:
    type: "s3"
    format: "json"
    bucket: "REPLACEME"
    prefix: "promsum/memory_by_pod"
  queries:
  - "get-memory-by-pod"
