reporting-operator:
  spec:
    config:
      prometheusURL: "http://prometheus.tectonic-system.svc.cluster.local:9090/"
presto:
  spec:
    presto:
      securityContext:
        fsGroup: 0
    hive:
      securityContext:
        fsGroup: 0

hdfs:
  spec:
    enabled: true
    config:
      datanodeDataDirPerms: "775"
    securityContext:
      fsGroup: 0
