apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  storage:
    type: hive
    # hive:
    #   type: "s3"
    #   s3:
    #     bucket: "bucketname/path/"
    #     secretName: "my-aws-secret"
