apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
     config:
       defaultStorage:
         create: true
         name: "local-storage"
         isDefault: true
         type: "hive"
         hive:
           tableProperties:
             location: "/user/hive/warehouse"

  presto:
    spec:
      config:
        sharedVolume:
          enabled: true
          storage:
            persistentVolumeClaimStorageClass: REPLACEME

  hdfs:
    enabled: false
