apiVersion: metering.openshift.io/v1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
    spec:
      image:
        repository: quay.io/openshift/origin-metering-reporting-operator
        tag: latest
