apiVersion: metering.openshift.io/v1alpha1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  storage:
    hive:
      type: "sharedPVC"
      sharedPVC:
        claimName: "metering-nfs"
        # uncomment the lines below to provision a new PVC using the specified
        # storageClass.
        # createPVC: true
        # storageClass: "my-nfs-storage-class"
        # size: 5Gi
