apiVersion: metering.openshift.io/v1alpha1
kind: MeteringConfig
metadata:
  name: "operator-metering"
spec:
  defaultStorage:
    type: "hive"
    hive:
      # instructs reporting-operator to create a new database in Hive
      unmanagedDatabase: false
      # feel free to adjust the database name  and location
      databaseName: "metering-nfs"
      location: "/user/hive/warehouse"

  presto:
    spec:
      config:
        sharedVolume:
          enabled: true
          storage:
            # change REPLACEME to the name of your PVC
            persistentVolumeClaimStorageClass: REPLACEME
            # mountPath must match the value of the location specified above.
            mountPath: "/user/hive/warehouse"
      hive:
        config:
          # set to false when spec.hadoop.spec.hdfs.enabled is false
          useHdfsConfigMap: false
          # Replace this with your path
          metastoreWarehouseDir: "/user/hive/warehouse"

  hadoop:
    spec:
      hdfs:
        # disable HDFS components when using S3 to avoid wasting resources.
        enabled: false
