{{- $operatorValues :=  index .Values "reporting-operator" -}}
{{- if $operatorValues.spec.config.tls.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $operatorValues.spec.config.tls.secretName }}
  labels:
    app: reporting-operator
type: kubernetes.io/tls
data:
  tls.crt: {{ $operatorValues.spec.config.tls.certificateData | b64enc | quote }}
  tls.key: {{ $operatorValues.spec.config.tls.privateKeyData | b64enc | quote }}
{{- end -}}
