{{- $operatorValues :=  index .Values "reporting-operator" -}}
{{- if $operatorValues.spec.config.prometheusCertificateAuthority.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $operatorValues.spec.config.prometheusCertificateAuthority.configMap.name }}
  labels:
    app: reporting-operator
data:
  {{ $operatorValues.spec.config.prometheusCertificateAuthority.configMap.filename | quote }}: {{ $operatorValues.spec.config.prometheusCertificateAuthority.configMap.value | quote }}
{{- end }}
