apiVersion: operators.coreos.com/v1
kind: CatalogSource
metadata:
  name: installed-upstream-metering-operators-metering
  namespace: marketplace
spec:
  targetNamespace: metering
  packages: metering-upstream
  source: upstream-community-operators

