---

meteringconfig_chart_path: "{{ lookup('env','HELM_CHART_PATH') }}"
meteringconfig_prune_label_key: 'metering.openshift.io/prune'
meteringconfig_prune_namespace_label_key: 'metering.openshift.io/ns-prune'

meteringconfig_default_values_file: "{{ meteringconfig_chart_path + '/values.yaml' }}"
meteringconfig_default_values: "{{ lookup('file', meteringconfig_default_values_file) | from_yaml }}"

# contains the users overrides
meteringconfig_spec_overrides: "{{ _metering_openshift_io_meteringconfig.spec }}"

# The default specs for each component
_presto_default_spec: "{{ meteringconfig_default_values.presto.spec }}"
_reporting_op_default_spec: "{{ meteringconfig_default_values['reporting-operator'].spec }}"
_hadoop_default_spec: "{{ meteringconfig_default_values.hadoop.spec }}"

# Default image repository and tag from the defaults
meteringconfig_reporting_operator_default_image_repo: "{{ _reporting_op_default_spec.image.repository }}"
meteringconfig_reporting_operator_default_image_tag: "{{ _reporting_op_default_spec.image.tag }}"
meteringconfig_presto_default_image_repo: "{{ _presto_default_spec.presto.image.repository }}"
meteringconfig_presto_default_image_tag: "{{ _presto_default_spec.presto.image.tag }}"
meteringconfig_hive_default_image_repo: "{{ _presto_default_spec.hive.image.repository }}"
meteringconfig_hive_default_image_tag: "{{ _presto_default_spec.hive.image.tag }}"
meteringconfig_hadoop_default_image_repo: "{{ _hadoop_default_spec.image.repository }}"
meteringconfig_hadoop_default_image_tag: "{{ _hadoop_default_spec.image.tag }}"

_storage_spec: "{{ meteringconfig_default_values | combine(meteringconfig_spec_overrides) | json_query('storage') | default({}, true) }}"

# Override the default images we use with env vars if set, falling back to the values.yaml configured default if not set.
meteringconfig_default_image_overrides:
  reporting-operator:
    spec:
      image:
        repository: "{{ lookup('env','METERING_REPORTING_OPERATOR_IMAGE').split(':')[0] | default(meteringconfig_reporting_operator_default_image_repo, true) }}"
        tag: "{{ lookup('env','METERING_REPORTING_OPERATOR_IMAGE').split(':')[1] | default(meteringconfig_reporting_operator_default_image_tag, true) }}"
  presto:
    spec:
      presto:
        image:
          repository: "{{ lookup('env','METERING_PRESTO_IMAGE').split(':')[0] | default(meteringconfig_presto_default_image_repo, true) }}"
          tag: "{{ lookup('env','METERING_PRESTO_IMAGE').split(':')[1] | default(meteringconfig_presto_default_image_tag, true) }}"
      hive:
        image:
          repository: "{{ lookup('env','METERING_HIVE_IMAGE').split(':')[0] | default(meteringconfig_hive_default_image_repo, true) }}"
          tag: "{{ lookup('env','METERING_HIVE_IMAGE').split(':')[1] | default(meteringconfig_hive_default_image_tag, true) }}"
  hadoop:
    spec:
      image:
        repository: "{{ lookup('env','METERING_HADOOP_IMAGE').split(':')[0] | default(meteringconfig_hadoop_default_image_repo, true) }}"
        tag: "{{ lookup('env','METERING_HADOOP_IMAGE').split(':')[1] | default(meteringconfig_hadoop_default_image_tag, true) }}"

_storage_overrides:
  s3:
    reporting-operator:
      spec:
        config:
          awsCredentialsSecretName: "{{ _storage_spec | json_query('hive.s3.awsCredentialsSecretName') }}"
          createAwsCredentialsSecret: false
    presto:
      spec:
        config:
          awsCredentialsSecretName: "{{ _storage_spec | json_query('hive.s3.awsCredentialsSecretName') }}"
          createAwsCredentialsSecret: false
        hive:
          config:
            metastoreWarehouseDir: "s3a://{{ _storage_spec | json_query('hive.s3.bucket') }}"
    hadoop:
      spec:
        config:
          defaultFS: "s3a://{{ _storage_spec | json_query('hive.s3.bucket') }}"
        hdfs:
          enabled: false

  hdfs:
    hadoop:
      spec:
        config:
          defaultFS: "hdfs://{{ _storage_spec | json_query('hive.hdfs.namenode') | default('hdfs-namenode-0.hdfs-namenode:9820', true) }}"
        hdfs:
          enabled: "{{ meteringconfig_spec_overrides | json_query('unsupportedFeatures.enableHDFS') | default(false, true) }}"

  sharedPVC:
    presto:
      spec:
        config:
          sharedVolume:
            enabled: true
            createPVC: "{{ _storage_spec | json_query('hive.sharedPVC.createPVC') | default(false, true) }}"
            mountPath: "{{ _storage_spec | json_query('hive.sharedPVC.mountPath') | default('/user/hive/warehouse', true) }}"
            claimName: "{{ _storage_spec | json_query('hive.sharedPVC.claimName') | default(_presto_default_spec.config.sharedVolume.claimName, true) }}"
            size: "{{ _storage_spec | json_query('hive.sharedPVC.size') | default(_presto_default_spec.config.sharedVolume.size, true) }}"
            storageClass: "{{ _storage_spec | json_query('hive.sharedPVC.storageClass') | default(_presto_default_spec.config.sharedVolume.storageClass, true) }}"
        hive:
          config:
            metastoreWarehouseDir: "{{ _storage_spec | json_query('hive.sharedPVC.mountPath') | default('/user/hive/warehouse', true) }}"

    hadoop:
      spec:
        config:
          defaultFS: "file://{{ _storage_spec | json_query('hive.sharedPVC.mountPath') | default('/user/hive/warehouse', true) }}"
        hdfs:
          enabled: false

meteringconfig_storage_hive_storage_type: "{{ _storage_spec | json_query('hive.type') }}"
meteringconfig_storage_overrides: "{{ _storage_overrides[meteringconfig_storage_hive_storage_type] | default({}, true) }}"

meteringconfig_spec: "{{ meteringconfig_default_values | combine(meteringconfig_default_image_overrides, meteringconfig_storage_overrides, meteringconfig_spec_overrides, recursive=True) }}"

meteringconfig_storage_s3_create_bucket: "{{ meteringconfig_spec | json_query('storage.hive.s3.createBucket') | default(true, true) }}"
# Intentionally an invalid default name to ensure that this is overridden, and obvious when it's not.
_default_metering_bucket_name: "-unconfigured-metering-bucket-name-"
meteringconfig_storage_s3_bucket_name: "{{ (meteringconfig_spec | json_query('storage.hive.s3.bucket') | default(_default_metering_bucket_name, true)).split('/')[0] }}"
meteringconfig_storage_s3_bucket_region: "{{ meteringconfig_spec | json_query('storage.hive.s3.region') | default(omit, true) }}"
meteringconfig_storage_s3_aws_credentials_secret_name: "{{ meteringconfig_spec | json_query('storage.hive.s3.awsCredentialsSecretName') | default(omit, true) }}"

########################
# All Variables below are setup to consume the result of merging the defaults, internal overrides, and user overrides.
########################

# Private variables to reduce boilerplate
_monitoring_conf: "{{ meteringconfig_spec.monitoring }}"
_openshift_reporting_spec: "{{ meteringconfig_spec['openshift-reporting'].spec }}"
_presto_spec: "{{ meteringconfig_spec.presto.spec }}"
_reporting_op_spec: "{{ meteringconfig_spec['reporting-operator'].spec }}"
_hadoop_spec: "{{ meteringconfig_spec.hadoop.spec }}"

meteringconfig_create_metering_default_storage: "{{ _openshift_reporting_spec.defaultStorageLocation.create | default(true) }}"

meteringconfig_create_metering_monitoring_resources: "{{ _monitoring_conf.enabled | default(true) }}"
meteringconfig_create_metering_monitoring_rbac: "{{ _monitoring_conf.enabled and _monitoring_conf.enabled and _monitoring_conf.createRBAC | default(true) }}"

meteringconfig_enable_reporting_aws_billing: "{{ _openshift_reporting_spec.awsBillingReportDataSource.enabled | default(false) }}"

meteringconfig_enable_hdfs: "{{ _hadoop_spec.hdfs.enabled | default(true) }}"
meteringconfig_create_hadoop_aws_credentials: "{{ _hadoop_spec.config.aws.createCredentialsSecret | default(false) }}"

meteringconfig_create_hive_metastore_pvc: "{{ _presto_spec.hive.metastore.storage.create | default(true) }}"
meteringconfig_create_presto_shared_volume_pvc: "{{ _presto_spec.config.sharedVolume.enabled and _presto_spec.config.sharedVolume.createPVC | default(false) }}"
meteringconfig_create_presto_aws_credentials: "{{ _presto_spec.config.createAwsCredentialsSecret | default(false) }}"
meteringconfig_create_presto_tls_secrets: "{{ _presto_spec.presto.config.tls.enabled and _presto_spec.presto.config.tls.createSecret | default(false) }}"
meteringconfig_create_presto_auth_secrets: "{{ _presto_spec.presto.config.auth.enabled and _presto_spec.presto.config.auth.createSecret | default(false) }}"

meteringconfig_create_reporting_operator_auth_proxy_cookie_secret: "{{ _reporting_op_spec.authProxy.enabled and _reporting_op_spec.authProxy.createCookieSecret | default(true) }}"
meteringconfig_create_reporting_operator_auth_proxy_htpasswd_secret: "{{ _reporting_op_spec.authProxy.enabled and _reporting_op_spec.authProxy.createHtpasswdSecret | default(true) }}"
meteringconfig_create_reporting_operator_auth_proxy_authenticated_emails_secret: "{{ _reporting_op_spec.authProxy.enabled and _reporting_op_spec.authProxy.createAuthenticatedEmailsSecret | default(true) }}"
meteringconfig_create_reporting_operator_auth_proxy_rbac: "{{ _reporting_op_spec.authProxy.enabled and (_reporting_op_spec.authProxy.subjectAccessReviewEnabled and _reporting_op_spec.authProxy.delegateURLsEnabled) | default(false) }}"
meteringconfig_create_reporting_operator_prometheus_bearer_token: "{{ _reporting_op_spec.config.prometheusImporter.auth.tokenSecret.create | default(false) }}"
meteringconfig_create_reporting_operator_prometheus_certificate_authority: "{{ _reporting_op_spec.config.prometheusCertificateAuthority.configMap.create | default(false) }}"
meteringconfig_create_reporting_operator_aws_credentials: "{{ _reporting_op_spec.config.createAwsCredentialsSecret | default(false) }}"
meteringconfig_create_reporting_operator_presto_tls_secrets: "{{ _reporting_op_spec.config.prestoTLS.enabled and _reporting_op_spec.config.prestoTLS.createSecret | default(false) }}"
meteringconfig_create_reporting_operator_presto_auth_secrets: "{{ _reporting_op_spec.config.prestoAuth.enabled and _reporting_op_spec.config.prestoAuth.createSecret | default(false) }}"
meteringconfig_create_reporting_operator_tls_secrets: "{{ _reporting_op_spec.config.tls.createSecret | default(false) }}"
meteringconfig_create_reporting_operator_route: "{{ _reporting_op_spec.route.enabled | default(false) }}"
meteringconfig_create_reporting_operator_cluster_monitoring_view_rbac: "{{ _reporting_op_spec.config.createClusterMonitoringViewRBAC | default(true) }}"
