reporting-operator:
  spec:
    config:
      prometheusURL: "http://prometheus-k8s.monitoring.svc:9090/"
      prestoMaxQueryLength: "10000000"
presto:
  spec:
    presto:
      config:
        maxQueryLength: "10000000"
      securityContext:
        fsGroup: 0
    hive:
      securityContext:
        fsGroup: 0

hdfs:
  spec:
    enabled: true
    config:
      datanodeDataDirPerms: "775"
    securityContext:
      fsGroup: 0

superset:
  enabled: false
  datasources:
  - fileName: "metering-presto.yaml"
    content: |-
      databases:
      - allow_ctas: true
        database_name: metering-presto
        expose_in_sqllab: true
        extra: "{\r\n    \"metadata_params\": {},\r\n    \"engine_params\": {},\r\n    \"\
          metadata_cache_timeout\": {},\r\n    \"schemas_allowed_for_csv_upload\": []\r\n\
          }\r\n"
        sqlalchemy_uri: presto://presto:8080
        tables: []
