apiVersion: v1
kind: Secret
metadata:
  name: metering-secrets
  labels:
    app: metering
{{- block "extraMetadata" . }}
{{- end }}
type: Opaque
data:
  aws-access-key-id: {{ .Values.config.awsAccessKeyID | b64enc | quote}}
  aws-secret-access-key: {{ .Values.config.awsSecretAccessKey | b64enc | quote}}
