apiVersion: v1
kind: ConfigMap
metadata:
  name: metering-config
  labels:
    app: metering
{{- block "extraMetadata" . }}
{{- end }}
data:
  log-reports: {{ .Values.config.logReports | quote}}
  log-ddl-queries: {{ .Values.config.logDDLQueries | quote}}
  log-dml-queries: {{ .Values.config.logDMLQueries | quote}}
  disable-promsum: {{ .Values.config.disablePromsum | quote}}
  prometheus-url: {{ required "a valid metering-operator.config.prometheusURL must be set" .Values.config.prometheusURL | quote}}
  promsum-poll-interval: {{ .Values.config.promsumPollInterval | quote}}
  promsum-chunk-size: {{ .Values.config.promsumChunkSize | quote}}
  promsum-step-size: {{ .Values.config.promsumStepSize | quote}}
  leader-lease-duration: {{ .Values.config.leaderLeaseDuration | quote }}
  presto-host: {{ .Values.config.prestoHost | quote }}
  hive-host: {{ .Values.config.hiveHost | quote }}
  use-tls: {{ .Values.config.tls.enabled | quote }}
