apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metering
  labels:
    app: metering
{{- block "extraMetadata" . }}
{{- end }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  template:
    metadata:
      labels:
        app: metering
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
{{- end }}
      annotations:
        metering-config-hash: {{ include (print $.Template.BasePath "/metering-config.yaml") . | sha256sum }}
{{- if .Values.config.createAwsCredentialsSecret }}
        metering-aws-credentials-secrets-hash: {{ include (print $.Template.BasePath "/metering-aws-credentials-secrets.yaml") . | sha256sum }}
{{- end }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: metering
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.config.awsCredentialsSecretName }}"
              key: aws-access-key-id
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.config.awsCredentialsSecretName }}"
              key: aws-secret-access-key
              optional: true
        - name: CHARGEBACK_LOG_DML_QUERIES
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: log-dml-queries
        - name: CHARGEBACK_LOG_DDL_QUERIES
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: log-ddl-queries
        - name: CHARGEBACK_LOG_REPORT
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: log-reports
        - name: CHARGEBACK_PROMETHEUS_HOST
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: prometheus-url
        - name: CHARGEBACK_PROMSUM_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: promsum-poll-interval
        - name: CHARGEBACK_PROMSUM_CHUNK_SIZE
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: promsum-chunk-size
        - name: CHARGEBACK_PROMSUM_STEP_SIZE
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: promsum-step-size
        - name: CHARGEBACK_DISABLE_PROMSUM
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: disable-promsum
        - name: CHARGEBACK_PRESTO_HOST
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: presto-host
        - name: CHARGEBACK_HIVE_HOST
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: hive-host
        - name: CHARGEBACK_LEASE_DURATION
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: leader-lease-duration
        - name: CHARGEBACK_USE_TLS
          valueFrom:
            configMapKeyRef:
              name: metering-config
              key: use-tls
        - name: CHARGEBACK_TLS_KEY
          value: "/tls/tls.key"
        - name: CHARGEBACK_TLS_CERT
          value: "/tls/tls.crt"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - name: "http"
          containerPort: 8080
        - name: "pprof"
          containerPort: 6060
        - name: "metrics"
          containerPort: 8082
{{- if .Values.config.tls.enabled -}}
{{- $_ := set .Values.readinessProbe.httpGet "scheme" "HTTPS" -}}
{{- $_ := set .Values.livenessProbe.httpGet "scheme" "HTTPS" -}}
{{- end }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
{{- if .Values.config.tls.enabled }}
        volumeMounts:
        - name: tls
          mountPath: /tls
{{- end }}
{{- if .Values.config.tls.enabled }}
      volumes:
      - name: tls
        secret:
          secretName: {{ .Values.config.tls.secretName }}
{{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccount: metering
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
