{{- if .Values.config.createAwsCredentialsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: metering-aws-credentials-secrets
  labels:
    app: metering
{{- block "extraMetadata" . }}
{{- end }}
type: Opaque
data:
{{- if .Values.config.awsAccessKeyID }}
  aws-access-key-id: {{ .Values.config.awsAccessKeyID | b64enc | quote}}
{{- end}}
{{- if .Values.config.awsSecretAccessKey }}
  aws-secret-access-key: {{ .Values.config.awsSecretAccessKey | b64enc | quote}}
{{- end}}
{{- end -}}
