apiVersion: v1
kind: Secret
metadata:
  name: hive-common-secrets
{{- block "extraMetadata" . }}
{{- end }}
data:
{{- if .Values.hive.config.dbConnectionUsername }}
  db-connection-username: {{ .Values.hive.config.dbConnectionUsername | b64enc | quote }}
{{- end }}
{{- if .Values.hive.config.dbConnectionPassword }}
  db-connection-password: {{ .Values.hive.config.dbConnectionPassword | b64enc | quote }}
{{- end }}
