apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-config
{{- block "extraMetadata" . }}
{{- end }}
data:
  log-level: {{ upper .Values.hive.config.logLevel | quote}}
  default-fs: {{ .Values.hive.config.defaultfs | quote}}
  db-connection-url: {{ .Values.hive.metastore.config.dbConnectionURL | quote}}
  db-connection-driver: {{ .Values.hive.metastore.config.dbConnectionDriver | quote}}
