apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-common-config
{{- block "extraMetadata" . }}
{{- end }}
data:
  environment: {{ .Values.spec.presto.config.environment | quote }}
  discovery-uri: {{ .Values.spec.presto.config.discoveryURI | quote }}
  hive-metastore-uri: {{ .Values.spec.presto.config.hiveMetastoreURI }}

