apiVersion: v1
kind: Secret
metadata:
  name: presto-catalog-config
  labels:
    app: presto
{{- block "extraMetadata" . }}
{{- end }}
type: Opaque
data:
  hive.properties: "{{ include "presto-hive-catalog-properties" . | b64enc }}"
  jmx.properties: "{{ include "presto-jmx-catalog-properties" . | b64enc }}"
{{- range $_, $connector := .Values.spec.presto.config.connectors.extraConnectorFiles }}
  {{ $connector.name }}: "{{ $connector.content | b64enc }}"
{{- end }}
