apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-coordinator-config
{{- block "extraMetadata" . }}
{{- end }}
data:
  log-level: {{ upper .Values.spec.presto.coordinator.config.logLevel | quote }}
  node-scheduler-include-coordinator: {{ .Values.spec.presto.coordinator.config.nodeSchedulerIncludeCoordinator | quote }}
{{- if .Values.spec.presto.coordinator.config.taskConcurrency }}
  task-concurrency: {{ .Values.spec.presto.coordinator.config.taskConcurrency | quote }}
{{- end }}
{{- if .Values.spec.presto.coordinator.config.taskMaxWorkerThreads }}
  task-max-worker-threads: {{ .Values.spec.presto.coordinator.config.taskMaxWorkerThreads | quote }}
{{- end }}
{{- if .Values.spec.presto.coordinator.config.taskMinDrivers }}
  task-min-drivers: {{ .Values.spec.presto.coordinator.config.taskMinDrivers | quote }}
{{- end }}
