apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: presto-worker
  labels:
    app: presto
    presto: worker
{{- block "extraMetadata" . }}
{{- end }}
spec:
  replicas: {{ .Values.spec.presto.worker.replicas }}
  selector:
    matchLabels:
      app: presto
      presto: worker
{{- if .Values.spec.presto.labels }}
{{ toYaml .Values.spec.presto.labels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: presto
        presto: worker
{{- if .Values.spec.presto.labels }}
{{ toYaml .Values.spec.presto.labels | indent 8 }}
{{- end }}
      annotations:
        presto-worker-config-hash: {{ include (print $.Template.BasePath "/presto-worker-config.yaml") . | sha256sum }}
        presto-common-config-hash: {{ include (print $.Template.BasePath "/presto-common-config.yaml") . | sha256sum }}
        presto-catalog-config-hash: {{ include (print $.Template.BasePath "/presto-catalog-config-secret.yaml") . | sha256sum }}
        presto-jmx-config-hash: {{ include (print $.Template.BasePath "/presto-jmx-config.yaml") . | sha256sum }}
{{- if .Values.spec.presto.annotations }}
{{ toYaml .Values.spec.presto.annotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.spec.presto.securityContext }}
      securityContext:
{{ toYaml .Values.spec.presto.securityContext | indent 8 }}
{{- end }}
{{- if .Values.spec.presto.worker.affinity }}
      affinity:
{{ toYaml .Values.spec.presto.worker.affinity | indent 8 }}
{{- end }}
{{- if .Values.spec.presto.worker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.spec.presto.worker.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.spec.presto.worker.tolerations }}
      tolerations:
{{ toYaml .Values.spec.presto.worker.tolerations | indent 8 }}
{{- end }}
      initContainers:
      - name: copy-presto-config
        image: "{{ .Values.spec.presto.image.repository }}:{{ .Values.spec.presto.image.tag }}"
        imagePullPolicy: {{ .Values.spec.presto.image.pullPolicy }}
        command: ['bash', '-c']
        # Copy the mounted configuration data into the presto-etc emptyDir volume so we can write to the config files
        args: ['cp -v -L -r -f /presto-etc/* /opt/presto/presto-server/etc/']
        env:
{{- include "presto-common-env" . | indent 8 }}
        volumeMounts:
        - name: presto-etc
          mountPath: /opt/presto/presto-server/etc
        - name: presto-worker-config
          mountPath: /presto-etc
        - name: presto-catalog-config
          mountPath: /presto-etc/catalog
        - name: presto-data
          mountPath: /var/presto/data
        resources:
{{ toYaml .Values.spec.presto.worker.resources | indent 10 }}
      containers:
      - name: presto
        image: "{{ .Values.spec.presto.image.repository }}:{{ .Values.spec.presto.image.tag }}"
        imagePullPolicy: {{ .Values.spec.presto.image.pullPolicy }}
        command: ['/presto-common/entrypoint.sh']
        args: ['/opt/presto/presto-server/bin/launcher', 'run']
        env:
        - name: JAVA_MAX_MEM_RATIO
          value: "{{ .Values.spec.presto.worker.config.jvm.percentMemoryLimitAsHeap }}"
          optional: true
{{- include "presto-common-env" . | indent 8 }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 8082
          protocol: TCP
        volumeMounts:
        - name: presto-etc
          mountPath: /opt/presto/presto-server/etc
        - name: presto-common-config
          mountPath: /presto-common
        - name: presto-jmx-config
          mountPath: /opt/jmx_exporter/config
        - name: presto-data
          mountPath: /var/presto/data
        - name: presto-logs
          mountPath: /var/presto/logs
{{- if .Values.spec.config.sharedVolume.enabled }}
        - name: hive-warehouse-data
          mountPath: {{ .Values.spec.config.sharedVolume.mountPath }}
{{- end }}
        resources:
{{ toYaml .Values.spec.presto.worker.resources | indent 10 }}
      volumes:
      - name: presto-worker-config
        configMap:
          name: presto-worker-config
      - name: presto-common-config
        configMap:
          name: presto-common-config
          defaultMode: 0774
      - name: presto-catalog-config
        secret:
          secretName: presto-catalog-config
      - name: presto-jmx-config
        configMap:
          name: presto-jmx-config
      - name: presto-etc
        emptyDir: {}
      - name: presto-data
        emptyDir: {}
      - name: presto-logs
        emptyDir: {}
{{- if .Values.spec.config.sharedVolume.enabled }}
      - name: hive-warehouse-data
        persistentVolumeClaim:
          claimName: {{ .Values.spec.config.sharedVolume.persistentVolumeClaimName }}
{{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: presto
{{- if .Values.spec.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.spec.imagePullSecrets | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.spec.presto.worker.terminationGracePeriodSeconds }}
