apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-coordinator-config
  labels:
    app: presto
{{- block "extraMetadata" . }}
{{- end }}
data:
  log.properties: |
    com.facebook.presto={{ upper .Values.spec.presto.coordinator.config.logLevel }}

  node.properties: |
    node.data-dir=/var/presto/data
    node.environment=production

  config.properties: |
    http-server.http.port=8080
    jmx.rmiserver.port=8081
    coordinator=true
    discovery-server.enabled=true
    discovery.uri={{ .Values.spec.presto.config.discoveryURI }}
    node-scheduler.include-coordinator={{ .Values.spec.presto.coordinator.config.nodeSchedulerIncludeCoordinator }}
{{- if .Values.spec.presto.config.maxQueryLength }}
    query.max-length={{ .Values.spec.presto.config.maxQueryLength }}
{{- end }}
{{- if .Values.spec.presto.coordinator.config.taskConcurrency }}
    task.concurrency={{ .Values.spec.presto.coordinator.config.taskConcurrency }}
{{- end }}
{{- if .Values.spec.presto.coordinator.config.taskMaxWorkerThreads }}
    task.max-worker-threads: {{ .Values.spec.presto.coordinator.config.taskMaxWorkerThreads }}
{{- end }}
{{- if .Values.spec.presto.coordinator.config.taskMinDrivers }}
    task.min-drivers: {{ .Values.spec.presto.coordinator.config.taskMinDrivers }}
{{- end }}

  jvm.config: |
    -server
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:OnOutOfMemoryError=kill -9 %p
    -javaagent:/opt/jmx_exporter/jmx_exporter.jar=8082:/opt/jmx_exporter/config/config.yml
