apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: presto-coordinator
  labels:
    app: presto
    presto: coordinator
{{- block "extraMetadata" . }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presto
      presto: coordinator
{{- if .Values.presto.labels }}
{{ toYaml .Values.presto.labels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: presto
        presto: coordinator
{{- if .Values.presto.labels }}
{{ toYaml .Values.presto.labels | indent 8 }}
{{- end }}
      annotations:
        presto-coordinator-config-hash: {{ include (print $.Template.BasePath "/presto-coordinator-config.yaml") . | sha256sum }}
        presto-secrets-hash: {{ include (print $.Template.BasePath "/presto-secrets.yaml") . | sha256sum }}
{{- if .Values.presto.annotations }}
{{ toYaml .Values.presto.annotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.presto.securityContext }}
      securityContext:
{{ toYaml .Values.presto.securityContext | indent 8 }}
{{- end }}
{{- if .Values.presto.coordinator.affinity }}
      affinity:
{{ toYaml .Values.presto.coordinator.affinity | indent 8 }}
{{- end }}
      containers:
      - name: presto
        image: "{{ .Values.presto.image.repository }}:{{ .Values.presto.image.tag }}"
        imagePullPolicy: {{ .Values.presto.image.pullPolicy }}
        env:
        - name: "HIVE_CATALOG_hive_s3_aws___access___key"
          valueFrom:
            secretKeyRef:
              name: presto-secrets
              key: aws-access-key-id
        - name: "HIVE_CATALOG_hive_s3_aws___secret___key"
          valueFrom:
            secretKeyRef:
              name: presto-secrets
              key: aws-secret-access-key
        - name: PRESTO_LOG_com_facebook_presto
          valueFrom:
            configMapKeyRef:
              name: presto-coordinator-config
              key: log-level
        - name: PRESTO_CONF_discovery_uri
          valueFrom:
            configMapKeyRef:
              name: presto-coordinator-config
              key: discovery-uri
        - name: PRESTO_CONF_discovery___server_enabled
          value: "true"
        - name: PRESTO_CONF_coordinator
          value: "true"
        - name: PRESTO_CONF_node___scheduler_include___coordinator
          valueFrom:
            configMapKeyRef:
              name: presto-coordinator-config
              key: node-scheduler-include-coordinator
        - name: PRESTO_CONF_task_concurrency
          valueFrom:
            configMapKeyRef:
              name: presto-coordinator-config
              key: task-concurrency
              optional: true
        - name: PRESTO_CONF_task_max___worker___threads
          valueFrom:
            configMapKeyRef:
              name: presto-coordinator-config
              key: task-max-worker-threads
              optional: true
        - name: PRESTO_CONF_task_min___drivers
          valueFrom:
            configMapKeyRef:
              name: presto-coordinator-config
              key: task-min-drivers
              optional: true
        - name: PRESTO_NODE_node_environment
          valueFrom:
            configMapKeyRef:
              name: presto-coordinator-config
              key: environment
        - name: PRESTO_NODE_node_id
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: presto
              resource: requests.memory
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: presto
              resource: limits.memory
        - name: JAVA_MAX_MEM_RATIO
          value: "50"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: prometheus-jmx
          containerPort: 8082
          protocol: TCP
        volumeMounts:
        - name: presto-data
          mountPath: /var/presto/data
        resources:
{{ toYaml .Values.presto.coordinator.resources | indent 10 }}
      volumes:
      - name: presto-data
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: presto
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.presto.coordinator.terminationGracePeriodSeconds }}
