apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-worker-config
{{- block "extraMetadata" . }}
{{- end }}
data:
  log-level: {{ upper .Values.spec.presto.worker.config.logLevel | quote }}
{{- if .Values.spec.presto.worker.config.taskConcurrency }}
  task-concurrency: {{ .Values.spec.presto.worker.config.taskConcurrency | quote }}
{{- end }}
{{- if .Values.spec.presto.worker.config.taskMaxWorkerThreads }}
  task-max-worker-threads: {{ .Values.spec.presto.worker.config.taskMaxWorkerThreads | quote }}
{{- end }}
{{- if .Values.spec.presto.worker.config.taskMinDrivers }}
  task-min-drivers: {{ .Values.spec.presto.worker.config.taskMinDrivers | quote }}
{{- end }}
