apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-worker-config
{{- block "extraMetadata" . }}
{{- end }}
data:
  environment: {{ .Values.presto.config.environment | quote }}
  discovery-uri: {{ .Values.presto.config.discoveryURI | quote }}
  hive-metastore-uri: {{ .Values.presto.config.hiveMetastoreURI }}

  log-level: {{ upper .Values.presto.worker.config.logLevel | quote }}
{{- if .Values.presto.worker.config.taskConcurrency }}
  task-concurrency: {{ .Values.presto.worker.config.taskConcurrency | quote }}
{{- end }}
{{- if .Values.presto.worker.config.taskMaxWorkerThreads }}
  task-max-worker-threads: {{ .Values.presto.worker.config.taskMaxWorkerThreads | quote }}
{{- end }}
{{- if .Values.presto.worker.config.taskMinDrivers }}
  task-min-drivers: {{ .Values.presto.worker.config.taskMinDrivers | quote }}
{{- end }}
