operator:
  image:
    repository: image-registry.openshift-image-registry.svc:5000/openshift/ose-metering-ansible-operator
    tag: "v4.5"

olm:
  imageTags:
  - name: metering-ansible-operator
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/ose-metering-ansible-operator:v4.5
  - name: metering-reporting-operator
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/ose-metering-reporting-operator:v4.5
  - name: metering-presto
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/ose-metering-presto:v4.5
  - name: metering-hive
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/ose-metering-hive:v4.5
  - name: metering-hadoop
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/ose-metering-hadoop:v4.5
  - name: ghostunnel
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/ose-ghostunnel:v4.5
  - name: oauth-proxy
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/ose-oauth-proxy:v4.5

  skipARTPackage: true

  channels:
  - name: "4.5"
    currentCSV: metering-operator.v4.5.0
  csv:
    name : metering-operator-testing.v4.5.0
    version: "4.5.0"
    provider:
      name: Metering OCP testing

  packageName: metering-ocp-testing
  subscriptionName: metering-ocp-testing
  subscriptionChannel: stable

  catalogSourceConfigName: installed-custom-metering-operators-openshift-metering
  catalogSourceConfigNamespace: openshift-marketplace
  catalogSourceConfigTargetNamespace: openshift-metering
  telemeterManifestGeneration: false
