apiVersion: cron.coreos.com/v1
kind: Cron
metadata:
  name: 1-minute
spec:
  suspend: false
  schedule: "@every 20s"
  reportTemplate:
    metadata:
      generateName: minute
    spec:
      reportingStart: '2017-07-28T00:00:00Z'
      reportingEnd: '2017-07-29T00:00:00Z'
      chargeback:
        bucket: <Promsum bucket>
        prefix: <Promsum bucket prefix>
      aws:
        bucket: <AWS report data bucket>
        prefix: <AWS report prefix>
      output:
        bucket: <Output bucket>
        prefix: <Output prefix>
