presto:
  presto:
    securityContext:
      fsGroup: 0
  hive:
    securityContext:
      fsGroup: 0

hdfs:
  enabled: true
  config:
    datanodeDataDirPerms: "775"
  securityContext:
    fsGroup: 0
