chargeback-operator:
  image:
    tag: release-0.5.1

presto:
  presto:
    image:
      tag: release-0.5.1
  hive:
    image:
      tag: release-0.5.1

hdfs:
  enabled: true
  image:
    tag: release-0.5.1

