- name: Get metastore secret
  block:
  - name: Get Metastore storage credentials secret
    k8s_info:
      api_version: v1
      kind: Secret
      name: "{{ _hive_metastore_db_secretName }}"
      namespace: "{{ meta.namespace }}"
    register: hive_metastore_db_secret_buf

  - name: Create variables for the decoded username and password data
    set_fact:
      _hive_metastore_db_username: "{{ _hive_metastore_db_secret_buf_resources_first_index.data.username | b64decode }}"
      _hive_metastore_db_password: "{{ _hive_metastore_db_secret_buf_resources_first_index.data.password | b64decode }}"
    when:
    - hive_metastore_db_secret_buf is defined
    - _hive_metastore_db_secret_buf_resources_first_index | length > 0

  - name: Merge the two dictionaries together
    set_fact:
      meteringconfig_spec: "{{ meteringconfig_spec | combine(_hive_metastore_db_overrides, recursive=True) }}"
  vars:
    _hive_metastore_db_secret_buf_resources_first_index: "{{ hive_metastore_db_secret_buf.resources | first }}"
    _hive_metastore_db_secretName: "{{ meteringconfig_spec_overrides | json_query('hive.spec.config.db.secretName') }}"
  no_log: true
  when:
  - _hive_metastore_db_secretName is defined
  - _hive_metastore_db_secretName | length > 0
