apiVersion: v1
kind: ConfigMap
metadata:
  name: hdfs-config
{{- block "extraMetadata" . }}
{{- end }}
data:
  log-level: {{ upper .Values.spec.config.logLevel | quote }}
  default-fs: {{ printf "hdfs://%s:%d" .Values.spec.config.namenodeHost (int .Values.spec.config.namenodePort) | quote}}
  namenode-host: {{ .Values.spec.config.namenodeHost | quote}}
  datanode-data-dir-perms: {{ .Values.spec.config.datanodeDataDirPerms | quote}}
