apiVersion: v1
kind: ConfigMap
metadata:
  name: hdfs-config
{{- block "extraMetadata" . }}
{{- end }}
data:
  log-level: {{ upper .Values.config.logLevel | quote }}
  default-fs: {{ .Values.config.defaultfs | quote}}
  datanode-data-dir-perms: {{ .Values.config.datanodeDataDirPerms | quote}}
