# A headless service to create DNS records.
apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs-namenode
{{- block "extraMetadata" . }}
{{- end }}
spec:
  ports:
  - port: 9820
    name: fs
  clusterIP: None
  selector:
    app: hdfs-namenode

---

apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode-proxy
  labels:
    app: hdfs-namenode
{{- block "extraMetadata" . }}
{{- end }}
spec:
  ports:
  - port: 9820
    name: fs
  selector:
    app: hdfs-namenode

---
# A headless service for the web interface.
apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode-web
  labels:
    app: hdfs-namenode
{{- block "extraMetadata" . }}
{{- end }}
spec:
  ports:
  - port: 9870
    name: web
  selector:
    app: hdfs-namenode
---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs-namenode
{{- block "extraMetadata" . }}
{{- end }}
spec:
  serviceName: "hdfs-namenode"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hdfs-namenode
{{- if .Values.spec.namenode.labels }}
{{ toYaml .Values.spec.namenode.labels | indent 8 }}
{{- end }}
      annotations:
        hdfs-configmap-hash: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- if .Values.spec.namenode.annotations }}
{{ toYaml .Values.spec.namenode.annotations | indent 8 }}
{{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.spec.namenode.terminationGracePeriodSeconds }}
{{- if .Values.spec.securityContext }}
      securityContext:
{{ toYaml .Values.spec.securityContext | indent 8 }}
{{- end }}
{{- if .Values.spec.namenode.affinity }}
      affinity:
{{ toYaml .Values.spec.namenode.affinity | indent 8 }}
{{- end }}
{{- if .Values.spec.namenode.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.spec.namenode.nodeSelector | indent 8 }}
{{- end }}
      containers:
      - name: hdfs-namenode
        image: "{{ .Values.spec.image.repository }}:{{ .Values.spec.image.tag }}"
        imagePullPolicy: {{ .Values.spec.image.pullPolicy }}
        args: ["namenode-entrypoint.sh"]
        env:
        - name: CORE_CONF_fs_defaultFS
          valueFrom:
            configMapKeyRef:
              name: hdfs-config
              key: default-fs
        - name: CLUSTER_NAME
          value: hdfs-k8s
        - name: HADOOP_LOGLEVEL
          valueFrom:
            configMapKeyRef:
              name: hdfs-config
              key: log-level
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: hdfs-namenode
              resource: requests.memory
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: hdfs-namenode
              resource: limits.memory
        - name: JAVA_MAX_MEM_RATIO
          value: "50"
        ports:
        - containerPort: 9820
          name: fs
        - containerPort: 9870
          name: web
        volumeMounts:
        - name: hdfs-namenode-data
          mountPath: /hadoop/dfs/name
          # we use a subPath to avoid the lost+found directory at the root of
          # the volume effecting the hdfs formating
          subPath: hadoop/dfs/name
        # required for openshift
        - name: datanode-empty
          mountPath: /hadoop/dfs/data
        resources:
{{ toYaml .Values.spec.namenode.resources | indent 10 }}
      serviceAccount: hdfs
{{- if .Values.spec.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.spec.imagePullSecrets | indent 8 }}
{{- end }}
      volumes:
      - name: datanode-empty
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: "hdfs-namenode-data"
      labels:
        app: hdfs-namenode
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.spec.namenode.storage.class }}
      resources:
        requests:
          storage: {{ .Values.spec.namenode.storage.size }}
