apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reports.chargeback.coreos.com
spec:
  group: chargeback.coreos.com
  version: prealpha
  scope: Namespaced
  names:
    plural: reports
    kind: Report
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportgenerationqueries.chargeback.coreos.com
spec:
  group: chargeback.coreos.com
  version: prealpha
  scope: Namespaced
  names:
    plural: reportgenerationqueries
    singular: reportgenerationquery
    kind: ReportGenerationQuery
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportprometheusqueries.chargeback.coreos.com
spec:
  group: chargeback.coreos.com
  version: prealpha
  scope: Namespaced
  names:
    plural: reportprometheusqueries
    singular: reportprometheusquery
    kind: ReportPrometheusQuery
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportdatastores.chargeback.coreos.com
spec:
  group: chargeback.coreos.com
  version: prealpha
  scope: Namespaced
  names:
    plural: reportdatastores
    singular: reportdatastore
    kind: ReportDataStore
