apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "superset.fullname" . }}
  labels:
    app: {{ template "superset.name" . }}
    chart: {{ template "superset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- block "extraMetadata" . }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "superset.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "superset.fullname" . }}
      labels:
        app: {{ template "superset.name" . }}
        chart: {{ template "superset.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 8 }}
{{- end }}
      annotations:
        superset-scripts-config-hash: {{ include (print $.Template.BasePath "/scripts-configmap.yaml") . | sha256sum }}
        superset-env-secret-hash: {{ include (print $.Template.BasePath "/env-secret.yaml") . | sha256sum }}
        superset-config-secret-hash: {{ include (print $.Template.BasePath "/server-config-secret.yaml") . | sha256sum }}
        superset-datasources-config-hash: {{ include (print $.Template.BasePath "/datasources-configmap.yaml") . | sha256sum }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
      volumes:
        - name: superset-scripts
          configMap:
            name: {{ template "superset.fullname" . }}-scripts
            defaultMode: 0774
        - name: superset-server-config
          secret:
            secretName: {{ template "superset.fullname" . }}-config
        - name: superset-datasources-config
          configMap:
            name: {{ template "superset.fullname" . }}-datasources
        - name: storage-volume
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "superset.fullname" . }}{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      initContainers:
        - name: superset-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/superset-scripts/entrypoint.sh"]
          args: ["/superset-scripts/init_superset.sh"]
          volumeMounts:
            - name: superset-server-config
              mountPath: /etc/superset
            - name: superset-scripts
              mountPath: /superset-scripts
            - name: superset-datasources-config
              mountPath: /superset-datasources
            - name: storage-volume
              mountPath: /var/lib/superset
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          env:
            - name: "DATASOURCES_DIRECTORY"
              value: "/superset-datasources"
          {{- range $key, $value := .Values.extraEnv }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ template "superset.fullname" . }}-env
        {{- if .Values.extraEnvFromSecret }}
            - secretRef:
                name: {{ .Values.extraEnvFromSecret }}
        {{- end }}
    {{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
    {{- end }}
      containers:
        - name: superset
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/superset-scripts/entrypoint.sh"]
          args: ["gunicorn", "superset:app" ]
          volumeMounts:
            - name: superset-server-config
              mountPath: /etc/superset
            - name: superset-scripts
              mountPath: /superset-scripts
            - name: superset-datasources-config
              mountPath: /superset-datasources
            - name: storage-volume
              mountPath: /var/lib/superset
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          env:
            - name: "DATASOURCES_DIRECTORY"
              value: "/superset-datasources"
          {{- range $key, $value := .Values.extraEnv }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ template "superset.fullname" . }}-env
        {{- if .Values.extraEnvFromSecret }}
            - secretRef:
                name: {{ .Values.extraEnvFromSecret }}
        {{- end }}
    {{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.livenessProbe }}
          livenessProbe:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.readinessProbe }}
          readinessProbe:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
