apiVersion: v1
kind: Secret
metadata:
  name: {{ template "superset.fullname" . }}-config
  labels:
    app: {{ template "superset.name" . }}
    chart: {{ template "superset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- block "extraMetadata" . }}
{{- end }}
type: Opaque
data:
  superset_config.py: {{ .Values.configFile | b64enc | quote }}
