---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.spec.config.allNamespaces }}
kind: ClusterRole
{{- else }}
kind: Role
{{- end }}
metadata:
  name: reporting-operator
  labels:
    app: reporting-operator
{{- block "extraMetadata" . }}
{{- end }}
rules:
# grants access to all core metering types which the reporting-operator uses
- apiGroups: ["metering.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
# grants access to leader election lock based on configmaps
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - patch
  - update
  - watch
# grants access to creating and updating events
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.spec.config.allNamespaces }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: reporting-operator
  labels:
    app: reporting-operator
{{- block "extraMetadata" . }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.spec.config.allNamespaces }}
  kind: ClusterRole
{{- else }}
  kind: Role
{{- end }}
  name: reporting-operator
subjects:
- kind: ServiceAccount
  name: reporting-operator
