{{- if .Values.spec.config.prometheusImporter.auth.tokenSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.spec.config.prometheusImporter.auth.tokenSecret.name }}
  labels:
    app: reporting-operator
{{- block "extraMetadata" . }}
{{- end }}
data:
  token: {{ .Values.spec.config.prometheusImporter.auth.tokenSecret.value | b64enc | quote }}
{{- end -}}
