apiVersion: metering.openshift.io/v1
kind: Report
metadata:
  name: cluster-cpu-usage-daily
spec:
  query: "cluster-cpu-usage"
  # this configures the this report to aggregate the hourly one
  inputs:
  - name: ClusterCpuusageReportName
    value: cluster-cpu-usage-hourly
  schedule:
    period: "daily"

---

apiVersion: metering.openshift.io/v1
kind: Report
metadata:
  name: cluster-memory-usage-daily
spec:
  query: "cluster-memory-usage"
  # this configures the this report to aggregate the hourly one
  inputs:
  - name: ClusterMemoryusageReportName
    value: cluster-memory-usage-hourly
  schedule:
    period: "daily"
