{{- if .Values.config.awsBillingDataSource.enabled -}}
apiVersion: chargeback.coreos.com/v1alpha1
kind: ReportDataStore
metadata:
  name: "aws-billing"
  labels:
    tectonic-chargeback: "true"
{{- block "extraMetadata" . }}
{{- end }}
spec:
  awsBilling:
    source:
      bucket: {{ .Values.config.awsBillingDataSource.bucket | quote }}
      prefix: {{ .Values.config.awsBillingDataSource.prefix | quote }}
{{- end -}}
